### ISSUE TITLE
Setting first day of week

### ISSUE THREAD

**Issue by borisjoskic** [diptanshumahish/calendify#1]
Is there an option to set first day of week? Currently, its SUN, which causes difference if our calendar is set to start from MON.

That forces us to remove one element from previousMonth type so we get correct dates displayed.

**Comment by diptanshumahish** [comment]
> Is there an option to set first day of week? Currently, its SUN, which causes difference if our calendar is set to start from MON.
> 
> 
> 
> That forces us to remove one element from previousMonth type so we get correct dates displayed.

it's not there currently, I'll surely add that by the next update.

**Comment by diptanshumahish** [comment]
This issue has been solved with version 3.0.0, there is an optional parameter for "startDateMonday", with prevMonth, nextMonth and getCalendar, that allows you to set your week starting from Monday.  @borisjoskic
